services:
  postgres:
    image: postgres:15
    container_name: medisistema_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      # puerto_pc:puerto_contenedor
      - "${DB_PORT}:5432"

    volumes:
      - medisistema_pgdata:/var/lib/postgresql/data

      # 01: esquema
      - ./.agents/MediSistema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

      # 02: seed
      - ./docker/init/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  medisistema_pgdata: